# Generated by Django 5.2 on 2025-04-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screencontrol',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='screencontrol',
            name='news',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screencontrol',
            name='temperature',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='screencontrol',
            name='weather',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
