# Generated by Django 5.2 on 2025-05-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_screencontrol_city_screencontrol_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screencontrol',
            name='fuel_city',
            field=models.CharField(default='ANKARA', max_length=16),
            preserve_default=False,
        ),
    ]
