# Generated by Django 5.2 on 2025-05-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_alter_screencontrol_fuel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screencontrol',
            name='fuel_city',
        ),
        migrations.AlterField(
            model_name='screencontrol',
            name='city',
            field=models.CharField(choices=[('ADANA', 'ADANA'), ('ADIYAMAN', 'ADIYAMAN'), ('AFYON', 'AFYON'), ('AGRI', 'AGRI'), ('AKSARAY', 'AKSARAY'), ('AMASYA', 'AMASYA'), ('ANKARA', 'ANKARA'), ('ANTALYA', 'ANTALYA'), ('AYDIN', 'AYDIN'), ('BALIKESIR', 'BALIKESIR'), ('BARTIN', 'BARTIN'), ('BATMAN', 'BATMAN'), ('BILECIK', 'BILECIK'), ('BOLU', 'BOLU'), ('BURDUR', 'BURDUR'), ('BURSA', 'BURSA'), ('CANAKKALE', 'CANAKKALE'), ('CANKIRI', 'CANKIRI'), ('CORUM', 'CORUM'), ('DENIZLI', 'DENIZLI'), ('DIYARBAKIR', 'DIYARBAKIR'), ('DUZCE', 'DUZCE'), ('EDIRNE', 'EDIRNE'), ('ELAZIĞ', 'ELAZIĞ'), ('ERZINCAN', 'ERZINCAN'), ('ERZURUM', 'ERZURUM'), ('ESKISEHIR', 'ESKISEHIR'), ('GAZİANTEP', 'GAZİANTEP'), ('GIRESUN', 'GIRESUN'), ('HATAY', 'HATAY'), ('ISPARTA', 'ISPARTA'), ('ISTANBUL', 'ISTANBUL'), ('IZMIR', 'IZMIR'), ('İÇEL', 'İÇEL'), ('K.MARAS', 'K.MARAS'), ('KARABUK', 'KARABUK'), ('KARAMAN', 'KARAMAN'), ('KASTAMONU', 'KASTAMONU'), ('KAYSERI', 'KAYSERI'), ('KIRIKKALE', 'KIRIKKALE'), ('KIRKLARELI', 'KIRKLARELI'), ('KIRSEHIR', 'KIRSEHIR'), ('KOCAELI', 'KOCAELI'), ('KONYA', 'KONYA'), ('KUTAHYA', 'KUTAHYA'), ('MALATYA', 'MALATYA'), ('MANISA', 'MANISA'), ('MARDİN', 'MARDİN'), ('MUGLA', 'MUGLA'), ('NEVSEHIR', 'NEVSEHIR'), ('NİĞDE', 'NİĞDE'), ('ORDU', 'ORDU'), ('OSMANIYE', 'OSMANIYE'), ('RIZE', 'RIZE'), ('SAKARYA', 'SAKARYA'), ('SAMSUN', 'SAMSUN'), ('SIVAS', 'SIVAS'), ('SİNOP', 'SİNOP'), ('ŞANLIURFA', 'ŞANLIURFA'), ('TEKIRDAG', 'TEKIRDAG'), ('TOKAT', 'TOKAT'), ('TRABZON', 'TRABZON'), ('USAK', 'USAK'), ('VAN', 'VAN'), ('YALOVA', 'YALOVA'), ('YOZGAT', 'YOZGAT'), ('ZONGULDAK', 'ZONGULDAK')], default='ANKARA', max_length=16),
            preserve_default=False,
        ),
    ]
